### ISSUE TITLE
Can't Collect static files

### ISSUE THREAD

**Issue by adetorodev** [Williano/django-bona-blog#10]
when I run python manage.py collectstatic I have this error

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/zestarlab/Django_projects/zestarlab/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/zestarlab/Django_projects/zestarlab/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/zestarlab/Django_projects/zestarlab/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/zestarlab/Django_projects/zestarlab/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/zestarlab/Django_projects/zestarlab/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 187, in handle
    collected = self.collect()
  File "/home/zestarlab/Django_projects/zestarlab/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 105, in collect
    for path, storage in finder.list(self.ignore_patterns):
  File "/home/zestarlab/Django_projects/zestarlab/lib/python3.8/site-packages/django/contrib/staticfiles/finders.py", line 130, in list
    for path in utils.get_files(storage, ignore_patterns):
  File "/home/zestarlab/Django_projects/zestarlab/lib/python3.8/site-packages/django/contrib/staticfiles/utils.py", line 23, in get_files
    directories, files = storage.listdir(location)
  File "/home/zestarlab/Django_projects/zestarlab/lib/python3.8/site-packages/django/core/files/storage.py", line 323, in listdir
    for entry in os.scandir(path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/zestarlab/Django_projects/zestarlab/zestarlab/blog/static'

**Comment by humair0143** [comment]
getting the same error

**Comment by Williano** [comment]
I work and fix this error get back to you
