### ISSUE TITLE
Migration 0004_article_deleted broken: Duplicate column name 'deleted'

### ISSUE THREAD

**Issue by kevin-olbrich** [Williano/django-bona-blog#6]
Fresh project using Dj 3.1.

```
File "/opt/dev/venv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/opt/dev/venv/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 73, in execute
    return self.cursor.execute(query, args)
  File "/opt/dev/venv/lib/python3.7/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/opt/dev/venv/lib/python3.7/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/opt/dev/venv/lib/python3.7/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (1060, "Duplicate column name 'deleted'")
```

**Comment by Williano** [comment]
Hi Kevin,

Thank you for bringing my attention to this. I will fix it and get back to you.

**Comment by Williano** [comment]
Try "python manage.py makemigrations" before doing "python manage.py migrate" and let me know

**Comment by hocnx** [comment]
@Williano 
I face the same problem.
> Try "python manage.py makemigrations" before doing "python manage.py migrate"
I tried this but this cannot help.
Progress stoped at `blog.0004_article_deleted... `

```
 Applying blog.0002_auto_20200618_2226... OK
  Applying blog.0003_auto_20200618_2322... OK
  Applying blog.0004_article_deleted...Traceback (most recent call last):
  File "/Users/tesuto/code/freema/myenv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)

.....
    raise errorclass(errno, errval)
django.db.utils.InternalError: (1060, "Duplicate column name 'deleted'")

```

**Comment by changeling** [comment]
Just to add here, there are a few migrations in the current version that are duplicated, and at least one that changes a default and should be an AlterField instead of an AddField.

**Comment by Williano** [comment]
Hi @changeling 


I will take a look at the migration issues and fix them as soon as I can. 

Thank you
